title: "Jade Mejean | Diététicienne nutritionniste"
description: "Jade Mejean, diététicienne nutritionniste à Villefranche de Lauragais (31)."
url: "https://r0ots.github.io"
baseurl: "/jmdiet2"
lang: fr

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _screenshots
