title: "Jade Mejean | Diététicienne nutritionniste"
description: "Jade Mejean, diététicienne nutritionniste à Villefranche de Lauragais (31)."
url: "https://www.jademejean-diet.fr"
baseurl: ""
lang: fr

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _screenshots
